import Header from "@/components/header";
import Home from "@/components/home";
import About from "@/components/about";
import Footer from "@/components/footer";
import Service from "@/components/service"
import type { Metadata } from "next";
import localFont from "next/font/local";
import '../styles/globals.css'


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Smart Elo Co., Ltd.",
  description: "Generated by Smart Elo Co., Ltd.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
        <Home/>
        <About/>
        <Service/>
        <Footer/>


      </body>
    </html>
  );
}
